---
title: "Ementa IRE 2021-01"
author: "Vitor Borges Jr."
date: "2021-01"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

# **Introdução ao R para Ecólogos - Programação para Análise de Dados e Reprodutibilidade na Ciência**

## **Sumário**

Aprender a programar em uma linguagem livre, como o R, expande consideravelmente as possibilidades para visualização e análise de dados na ecologia. Como gerar gráficos para descrever os dados? Como gerar gráficos que demonstrem a relação entre duas ou mais variáveis? Como executar a análise mais adequada para os diferentes tipos de dados? Esta disciplina tem como objetivo fornecer as ferramentas para executar essas tarefas a partir da linguagem R, além de oferecer novas ferramentas para redação de documentos, compartilhamento de projetos e controle de versão.

## **Ementa**

Tipo de objetos; indexação e lógica; controladores de fluxo; funções; manipulação, sumário e visualização de dados; distribuições de frequências; estatísticas descritivas; medidas de centralidade; medidas de variação; medidas de simetria; correlação; covariância; gráfico de barras; histograma; boxplots; gráfico de pontos; pacotes no R; tidyverse; tidyr; dplyr; ggplot2; bootstrapping; mínimos quadrados; máxima verossimilhança; teste de hipóteses; regressão linear; GLMs; GLMMs; glmTMB; ordenação; PCA; agrupamento; classificação; vegan; git; github; Rmarkdown.

### **Referências**

Crawley M.J. 2007. The R Book. Wiley. Doi: https://doi.org/10.1002/9780470515075

Xie Y., Allaire J.J., Grolemund G. 2021. R Markdown: The Definitive Guide. Chapman & Hall/CRC. https://bookdown.org/yihui/rmarkdown/

Wickham H., Grolemund G. 2017. R for Data Science. Visualize, Model, Tranform, Tidy and Import Data. O’Reilly. https://r4ds.had.co.nz/
