---
title: "Introdução ao R para Ecólogos"
author: "Vitor Borges Jr."
date: "2021-01"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

Este site contem os slides, scripts, dados e exercícios para a disciplina Introdução ao R para Ecólogos - Programação para Análise de Dados e Reprodutibilidade na Ciência ([ementa](Ementa-IRE.html)) minsitrado no Programa de Pós-Graduação em Biodiversidade da UNIRIO no primeiro semestre de 2021.

___

## **Material para a Disciplina**

Data  | Videos | Slides | Scripts | Exercícios | Respostas
------------- |----------- | ------------- | ------------- | ------------- | -------------
25 de maio  | [Objetos e Indexação - parte 1](https://drive.google.com/file/d/1oMMfNGMG4e2frOIwDDOQ64tr5QsdXgdu/view?usp=sharing)<br/> [Objetos e Indexação - parte 2](https://drive.google.com/file/d/1evZ3CT6Z5vrnvry8_hWW1snQDTvYtTtI/view?usp=sharing) | [Slides 01](Slides/01-Introducao-ao-R-Objetos-e-Indexacao-Slides.html) | [Script 01](Scripts/01-Introducao-ao-R-parte1.R) | - | -
1 de junho  | [Funções Loop](https://drive.google.com/file/d/1HpYO862-jBfSu_thZmDpzUz1nVnFVeXC/view?usp=sharing) | [Slides 02](Slides/02-Introducao-ao-R-Funcoes-Loop.html) | [Script 02](Scripts/02-Introducao-ao-R-parte-2.R) | [Exercícios 02](Exercícios/02-Exercícios-Funções-Loop-e-Funções.Rmd) | [Respostas 02](Respostas/02-Exercícios-Funções-Loop-e-Funções-respostas.nb.html)         
8 de junho  | [Funções e Controladores de Fluxo](https://drive.google.com/file/d/1_qmp_OLflgqaKo557jHRURG1-L2Q7zsy/view?usp=sharing) | [Slides 03](Slides/03-Introducao-ao-R-Introducao-Escrita-de-Funcoes-slides.html) | [Script 03](Scripts/03-Introducao-R-Funcoes-Controladores-de-fluxo.R) | [Exercícios 03](Exercícios/03-Exercícios-Funcoes-Controladores_de_Fluxo.Rmd) | [Respostas 03](Respostas/03-Exercícios-Funcoes-Controladores-de-Fluxo-respostas.nb.html)
15 de junho  | [Manipulação e Limpeza de Dados ](https://drive.google.com/file/d/1vte8UQ9Sk9efiPbe7xjzvsu4hoCGcxzZ/view?usp=sharing) | [Slides 04](Slides/04-Manipulação-e-Limpeza-de-Dados-slides.html) | [Script 04](Scripts/04-Limpeza-e-Manipulação-de-Dados.R) | [Exercícios 04](Exercícios/04-Exercícios-de-Limpeza-e-Manipulação-de-Dados.Rmd) | [Respostas 04](Respostas/04-Exercícios-de-Limpeza-e-Manipulação-de-Dados-respostas.nb.html)
22 de junho | [Manipulação e Transformação de Dados](https://drive.google.com/file/d/1SoovW58cGxEys1XFRQ7tcq-f1PiF54cl/view) | [Slides 05](Slides/05-Manipulação-e-Transformação-de-Dados-slides.html) | [Scripts 05](Scripts/05-Manipulação-e-Transformação-de-Dados.R) | - 
6 de julho | [Transformação e Visualização de Dados - parte 1](https://drive.google.com/file/d/1lCUhwFW4cQ6yTcwCv1LZTO_wDADb1tIe/view?usp=sharing)<br/>[Transformação e Visualização de Dados - parte 2](https://drive.google.com/file/d/1HIPZT-6U-4YFGjq1m3UPjwJEwY6xuJzl/view?usp=sharing)| [Slides 06](Slides/06-Transformação-e-Visualização-de-Dados.html) | [Scripts 06](Scripts/06 -Transformação-e-Visualização-de-Dados.R) | [Exercícios 06](Exercícios/06-Exercícios-Visualização-de-Dados.Rmd) | [Respostas 06](Respostas/06-Exercícios-Visualização-de-Dados-respostas.nb.html)
13 de julho | [Transformação e Visualização de Dados - parte 1](https://drive.google.com/file/d/1BPpOLLw0gn1yigmjo6gImLTWXLOIKb_Z/view)<br/>[Transformação e Visualização de Dados - parte 2](https://drive.google.com/file/d/1KjY6AC_aJdt_gVDdCVFI4F4Rf6AHvIFu/view)| [Slides 07](Slides/07-Visualizacao-de-Dados-com-ggplot2.html) | [Scripts 07](Scripts/07-Visualização-de-Dados-com-ggplot2.R) | [Exercícios 07]() | [Respostas 07]()

### Arquivos de Dados 

[IRE_functions.R](Slides/IRE_functions.R)\
[numero_de_especies.txt](Dados/numero_de_especies.txt)\
[area.csv](Dados/area.csv)\
[variavel_categorica1.xlsx](Dados/variavel_categorica1.xlsx)\
[variavel_categorica2.txt](Dados/variavel_categorica2.txt)\
[variavel_categorica3.csv](Dados/variavel_categorica3.csv)\
[tadpoles_raw.csv](Dados/tadpoles_raw.csv)\
[tadpoles_raw.xlsx](Dados/tadpoles_raw.xlsx)\
[streams.xlsx](Dados/streams.xlsx)\
[streams_variables.csv](Dados/streams_variables.csv)\
[streams_date_variables.csv](Dados/streams_date_variables.csv)\
